### ISSUE TITLE
Mixed Image Service references

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#75] opened 2018-12-28 17:29 UTC
## Mixed Image Service references

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
 (a mashup, with img2 and img3 services)

**Comment by glenrobson** [comment] 2022-01-21 18:18
Duplicate of #56?

**Closed** 2022-01-21 18:18 UTC
Labels: content: image, linking, meta:discuss, api: image, services/extensions, technical
