### ISSUE TITLE
Choice of Images

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#112] opened 2019-11-05 16:32 UTC
## Choice of Images

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  

There are multiple images available for a given View (Canvas). For example, a painting has been photographed in 10 different wavelengths of light. The images are congruent (?) - that is, they all line up.

**Comment by azaroth42** [comment] 2019-11-05 19:54
(Intentional) duplicate of #33; propose close ;)

**Comment by kirschbombe** [comment] 2022-03-09 00:29
Closed as duplicate to #33 - addressed with PR #115

**Closed by kirschbombe** 2022-03-09 00:29 UTC
Labels: meta: duplicate
